name: Generate Snake Animation

on:
  # 每天自动运行一次
  schedule:
    - cron: "0 0 * * *"
  # 允许手动触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 使用 Platane/snk 生成贪吃蛇动画
      - name: Generate GitHub contribution snake
        uses: Platane/snk@master
        with:
          github_user_name: 1parado
          outputs: dist/github-contribution-grid-snake.svg

      # 把生成的动画推送到 output 分支
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
